name: Deploy
on:
  push:
    branches:
      - main
env:
  MDBOOK_VERSION: 0.5.2
  MDBOOK_MERMAID_VERSION: 0.17.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Rust
      uses: metalbear-co/setup-rust-toolchain@009cda47e1b529982a00627a40eda87b4215035a
    - name: Install mdbook and mdbook-mermaid
      run: |
        cargo install mdbook --version ${{ env.MDBOOK_VERSION }} --locked
        cargo install mdbook-mermaid --version ${{ env.MDBOOK_MERMAID_VERSION }} --locked
    - name: Generate Book
      run: |
        ./generate-book.py
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./book

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
